language: php

php:
  - 7.1
  - 7.2
  - 7.3
env:
  - setup=stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

before_script:
  - composer run-script post-root-package-install
  - php artisan key:generate --ansi

script: vendor/bin/phpunit

notifications:
  email: false